Use `length.map(_ > 0)` instead of `exists`
This is to work around an issue in mariadb/j with slick. Weirdly this
works:

```
findQuery(namespace, id).exists.result
```

But not this

```
findQuery(namespace, id).exists.result.filter(_.status === ObjectStatus.UPLOADED)
```

Which fails with:

```
java.lang.ArrayIndexOutOfBoundsException: Index 304 out of bounds for length 279
```

slick compiles the failing query to:

```
select exists(select `namespace`, `object_id`, `size`, `status` from `object` where ((`object_id` = '87613bba50b17cea53869d2d46c4ae219f5f939c547a513c093dc503aefc4e74.commit') and (`namespace` = '5a54a798-d872-495f-87cd-ba164289e1dc')) and (`status` = 'UPLOADED'))
```

Which includes an unexpected parenthesis grouping, left associated,
which seems to be incompatible with the newer versions of mariadb/j.

Without the extra filer, this compiles to:

```
select exists(select `namespace`, `object_id`, `size`, `status` from `object` where (`object_id` = '87613bba50b17cea53869d2d46c4ae219f5f939c547a513c093dc503aefc4e74.commit') and (`namespace` = '5a54a798-d872-495f-87cd-ba164289e1dc'))
```

Note the parenthesis grouping, which doesn't associate to the left,
which does not error with the latest mariadb/j (3.0.5).